matrix:
  - JOB="./gradlew build"
script: "$JOB"

notifications:
  email: 
  slack: progettosw:KWgUv6xVIzpRsxYWt2YrLIM0

    recipients:
       - j.inglese@studenti.unisannio.it 
       - s.digiambattista1@studenti.unisannio.it 
    on_success: always
    on_failure: always
   
