language:
- java
- groovy

install: ./install-dependencies.sh
  
jobs:
 include:
  - stage: compile
    script: gradle build
 

notifications:
 
  slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy

  email: 

     recipients:
    
     - j.inglese@studenti.unisannio.it
     on_success: always
     on_failure: always
