language: java
install: skip

os: linux
dist: trusty
jdk:
  - openjdk11 
 
before_install:
 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
 
script:
  - ./gradlew build
  

notifications:
  slack: progettosw:DYwOQxciENXZRcleC0E0DgY4
  
  email: j.inglese@studenti.unisannio.it
         s.digiambattista1@studenti.unisannio.it
  on_success: always
  on_failure: always
