

jobs:
    include:
       - stage: build
         script: ./gradlew build
       - stage: check
          script: ./gradlew check   
       

notifications:

  slack: progettosw:4IlyRyROlLmCEaqUVSzx9bG5




