    
    matrix:
- JOB="./gradlew build"
script: "$JOB"

notifications:

  slack: progettosw:4IlyRyROlLmCEaqUVSzx9bG5

  email: 
    recipients:
     - s.digiambattista1@studenti.unisannio.it  
    on_success: always
    on_failure: always
