matrix:
  include:
    - language: java
        before_script: cd Tesiplugin
        script : gradle check
    
    - language: groovy
        before_script: cd Tesiplugin
        script : gradle compileGroovy
