matrix:
  include:
    - language: java
         script : cd Tesiplugin
           before_script: compile build
    - language: groovy
         script : cd Tesiplugin
           before_script: compile build
      
      notifications:
      
      slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy
      
      email: 

            recipients:
    
            - j.inglese@studenti.unisannio.it 
     
            on_success: always
            on_failure: always
