language:
- java
- groovy
script: cd Tesiplugin && gradle assemble 

notifications:
 
  slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy

  email: 

     recipients:
    
     - j.inglese@studenti.unisannio.it
     on_success: always
     on_failure: always
