language: java

os: linux
dist: trusty
jdk: openjdk11 
env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
        
before_install:
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
 
script:
  - ./gradlew build
  

notifications:
  slack: progettosw:Rx1NBVfPkgXKb2NGaSAjbKdR

  on_success: always
  on_failure: always
