language: java

os: linux
dist: trusty
jdk: openjdk-11-jre-headless 

before_install:
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
 
script:
  - ./gradlew build
  

notifications:
  slack: progettosw:Rx1NBVfPkgXKb2NGaSAjbKdR

  on_success: always
  on_failure: always
