language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
- cd Tesiplugin
- chmod +x gradlew
- ./gradlew clean
 
script:
- ./gradlew build  


notifications:
  slack: progettosw:1rOw47ik62k9gOvOg1rAGnkn
  
  on_success: always
  on_failure: always
