language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
- cd Tesiplugin
- chmod +x gradlew
- ./gradlew clean
 
matrix:
include: 
- script: ./gradlew build  

- script : cd buildSrc && chmod +x gradlew && ./gradlew build  

notifications:
   slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy
  
   on_success: always
   on_failure: always
