matrix:
- JOB="./gradlew build"

script: "$JOB"

notifications:
slack: progettosw:cHwelSuIlH4TSyeMiMYYaIZp
email:
recipients:
- j.inglese@studenti.unisannio.it 
- s.digiambattista1@studenti.unisannio.it 
on_success: always
on_failure: always
