language: java
install: skip

os: linux
dist: trusty
jdk:
  - openjdk8 
 
before_install:
  - sudo apt-get -y install libxml2-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
 
script:
  - ./gradlew build
  

notifications:
  slack: progettosw:DYwOQxciENXZRcleC0E0DgY4

  on_success: always
  on_failure: always
