language: java

os: linux
dist: trusty
jdk: oraclejdk11

before_install:
  - java-11-openjdk-headless
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
 
script:
  - ./gradlew build
  

notifications:
  slack: progettosw:Rx1NBVfPkgXKb2NGaSAjbKdR

  on_success: always
  on_failure: always
