language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
- cd Tesiplugin
- chmod +x gradlew
- ./gradlew clean
 
script: 
- ./gradlew build  
- builduild ddsdasd 

notifications:
   slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy
  
   on_success: always
   on_failure: always
