 
script: ./gradlew build"

notifications: 
 slack: progettosw:KWgUv6xVIzpRsxYWt2YrLIM0
  email: 
     recipients:
       - j.inglese@studenti.unisannio.it 
       - s.digiambattista1@studenti.unisannio.it 
    on_success: always
    on_failure: always
