language:
- java
- groovy
 

before_install:
 - cd Tesiplugin\gradle\wrapper && gradle wrapper

script: 
- cd Tesiplugin && gradle build

notifications:
 
  slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy

  email: 

     recipients:
    
     - j.inglese@studenti.unisannio.it
     on_success: always
     on_failure: always
