matrix:
  - JOB="./gradlew build"
script: "$JOB"

notifications:
 slack: progettosw:kj79uEamCYqrhNOGipadXZLb
  email:
    recipients:
       - s.digiambattista1@studenti.unisannio.it 
    on_success: always
    on_failure: always
