    
jobs:
    include:
       - stage: build
         script: ./gradlew build
       - stage: prova
         script: ./gradlew prova

notifications:

  slack: progettosw:4IlyRyROlLmCEaqUVSzx9bG5

  email: 
    recipients:
     - s.digiambattista1@studenti.unisannio.it  
    on_success: always
    on_failure: always
