matrix:
  - JOB="./gradlew build"
script: "$JOB"


notifications:
  slack: progettosw:bFuaa6DM29GcOUmWYvlwI10g
  email: 
     recipients:
       - j.inglese@studenti.unisannio.it 
    on_success: always
    on_failure: always
