language: java
install : skip

os: linux
dist: trusty
jdk:
  - openjdk8 
 
 
    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - cd Tesiplugin
  - chmod +x gradlew

 
script:
  - ./gradlew build
  
notifications:
 
  slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy

  email: 

     recipients:
    
     - j.inglese@studenti.unisannio.it
     on_success: always
     on_failure: always




