

jobs:
    include:
       - stage: build
         script: gradle build
       - stage: check
          script: gradle check   
       

notifications:

  slack: progettosw:4IlyRyROlLmCEaqUVSzx9bG5




