language: java

os: linux
dist: trusty
jdk: oraclejdk11

before_install:
  - cd Tesiplugin
  - chmod +x gradlew
  - ./gradlew clean
  - java -Djava.awt.headless=true

script:
  - ./gradlew build
  

notifications:
  slack: progettosw:Rx1NBVfPkgXKb2NGaSAjbKdR

  on_success: always
  on_failure: always
