language:
- java
- groovy

before_install:
  - wget http://services.gradle.org/distributions/gradle-6.7.1-bin.zip
  - unzip -qq gradle-6.7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v 
  
jobs:
 include:
  - stage: compile
    script: gradle build
 

notifications:
 
  slack: progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy

  email: 

     recipients:
    
     - j.inglese@studenti.unisannio.it
     on_success: always
     on_failure: always
