

jobs:
    include:
       - stage: build
         script: ./gradlew build
       - stage: check
          script: ./gradlew check   
       

notifications:

  slack: progettosw:Qq0akOe8O6Spiu1FjUmijk1U




