--- 
matrix: 
  include: 
    - 
      language: groovy && java
      script: "cd Tesiplugin && gradle build"
notifications: 
  email: 
    - j.inglese@studenti.unisannio.it
  slack: "progettosw:ygB8Ex6XUsdO8GlY1uOoAQoy"
